package com.aaronhuang.medintel.repository;

import java.time.Instant;
import java.util.List;
import java.util.UUID;
import org.springframework.stereotype.Repository;

import com.aaronhuang.medintel.domain.model.AvoidanceWindow;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;

/**
 * Repository for avoidance windows generated by interaction rules.
 *
 * <p>Used to retrieve active windows for a user at a given point in time during
 * intake evaluation.</p>
 */
@Repository
public interface AvoidanceWindowRepository extends JpaRepository<AvoidanceWindow, UUID> {
    /**
     * Finds avoidance windows that are active at the given timestamp.
     *
     * <p>A window is active when {@code startTime <= timestamp <= endTime}.</p>
     *
     * @param userId user identifier that owns the windows
     * @param timestamp UTC instant to check against the window bounds
     * @return active avoidance windows for the user at the given time
     */
    @Query("""
        SELECT aw FROM AvoidanceWindow aw
        WHERE aw.intakeEvent.user.id = :userId
        AND aw.startTime <= :ts
        AND aw.endTime >= :ts
        """) 
    List <AvoidanceWindow> findActiveWindows( 
        @Param("userId") UUID userId,
        @Param("ts") Instant timestamp
    );

    @Modifying
    @Query("""
        DELETE FROM AvoidanceWindow aw
        WHERE aw.endTime < :now
        """)
    void deleteExpiredWindows(@Param("now") Instant now);
}
